function A = floatsnake_connection(a1,a2)
%FLOATSNAKE_CONNECTION
%    A = FLOATSNAKE_CONNECTION(A1,A2)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    31-Aug-2016 15:49:32

t2 = a1+a2;
t3 = a1.*2.0;
t4 = cos(t2);
t5 = t4.*2.0;
t6 = cos(a1);
t7 = t6.*6.0;
t8 = cos(a2);
t9 = t8.*6.0;
t10 = t5+t7+t9+1.3e1;
t11 = 1.0./t10;
t12 = a2.*2.0;
t13 = sin(t2);
t14 = t13.*3.0;
t15 = sin(a1);
t16 = sin(a2);
t17 = a1-a2;
t18 = sin(t17);
t19 = t18.*9.0;
t20 = a1+t12;
t21 = sin(t20);
t22 = a2+t3;
t23 = sin(t22);
t24 = t4.*9.0;
t25 = cos(t17);
t26 = t25.*9.0;
t27 = cos(t20);
t28 = cos(t22);
A = reshape([t11.*(t14+t15.*2.1e1-t16.*7.0+t19-t21+t23+sin(t3).*3.0).*(1.0./1.2e1),t11.*(t6.*2.1e1+t8.*7.0+t24+t26+t27+t28+cos(t3).*3.0+3.0).*(1.0./1.2e1),-t11.*(t4+t6.*3.0+3.0),t11.*(t14-t15.*7.0+t16.*2.1e1-t19+t21-t23+sin(t12).*3.0).*(-1.0./1.2e1),t11.*(t6.*7.0+t8.*2.1e1+t24+t26+t27+t28+cos(t12).*3.0+3.0).*(1.0./1.2e1),t11.*(t4+t8.*3.0+3.0)],[3,2]);
